FROM php:8.2-fpm

WORKDIR /var/www/backend

RUN apt update && apt install -y libpng-dev libjpeg-dev libonig-dev zip unzip git curl && \
    docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

COPY . .

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install --no-dev --optimize-autoloader

CMD ["php-fpm"]
